version: '3.2'
services:
  postgres:
    image: "postgres:14"
    command: postgres -c 'max_connections=200'
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      # We bind only to 127.0.0.1, so setting insecure password is acceptable here
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=withdrawal-finalizer-db

volumes:
  pg_data:
